<?php 
 error_reporting(E_ALL);
 ini_set("display_errors", 1);
date_default_timezone_set("Asia/Calcutta");
 $option_indice  = array("BANKNIFTY","NIFTY");
 $option_stocks = array(
        "NIFTY",
        "BANKNIFTY",
//         "SUNPHARMA",
//         "HDFCBANK",
//         "HCLTECH",
//         "HINDALCO",
//         "INDUSINDBK",
//         "INFY",
//         "ITC",
//         "JSWSTEEL",
//         "KOTAKBANK",
//         "RELIANCE",
//         "SBIN",
//         "TATASTEEL",
//         "TATAMOTORS",
//         "TCS",
//         "WIPRO",
//         "TATACONSUM",
// "JINDALSTEL",
// "HINDUNILVR",
//     "ICICIBANK",
//     "DLF",
//      "AXISBANK",
);
//check lot size of options
//https://webapi.niftytrader.in/webapi/Stats/nseFnoNew
 $GLOBALS['option_chain_time'] = date("Y-m-d H:i:00");
 $GLOBALS['option_chain_date'] = date("Y-m-d");
 $GLOBALS['option_chain_timestamp'] = strtotime($option_chain_time);
$GLOBALS['nxt_th_month'] = date('Y-m-d', strtotime('+3 months')); 
$GLOBALS['set_cookie'] = get_nse_cookie(); 
$GLOBALS['set_cookiee'] = isset($GLOBALS['set_cookie']["set-cookie"]) ? $GLOBALS['set_cookie']["set-cookie"] : $GLOBALS['set_cookie']["Set-Cookie"];
// echo '<pre>';
// print_r($GLOBALS['set_cookiee']);
// echo '</pre>'; exit;
$GLOBALS['get_spot_price_symbol'] = array("NIFTY" => "NIFTY%2050", "BANKNIFTY" => "NIFTY%20BANK");
$GLOBALS['ignore_dates'] = array(
"2022-01-26","2022-03-01","2022-03-18","2022-04-01","2022-04-14","2022-04-15","2022-05-03","2022-05-16","2022-08-09","2022-08-15",
"2022-08-16","2022-08-31","2022-10-05","2022-10-20","2022-10-26","2022-11-08","2022-10-23","2022-10-30","2022-11-06","2022-11-13",
"2022-11-20","2022-11-27","2022-12-04","2022-12-11","2022-12-18","2022-12-25","2023-01-01","2023-01-08","2023-01-15","2023-01-22",
"2023-01-29","2023-02-05","2023-02-12","2023-02-19","2023-02-26","2023-03-05","2023-03-12","2023-03-19","2023-03-26","2023-04-02",
"2023-04-09","2023-04-16","2023-04-23","2023-04-30","2023-05-07","2023-05-14","2023-05-21","2023-05-28","2023-06-04","2023-06-11"
,"2023-06-18","2023-06-25","2023-07-02","2023-07-09","2023-07-16","2023-07-23","2023-07-30","2023-08-06","2023-08-13","2023-08-20",
"2023-08-27","2023-09-03","2023-09-10","2023-09-17","2023-09-24","2023-10-01","2023-10-08","2023-10-15","2023-10-22","2022-10-20","2022-10-26","2022-11-08"
);
//$ch = curl_init("https://www.nseindia.com/api/option-chain-equities?symbol=$op_stocks");
/*
 function get_op_eq($op_stocks, $req_count){
     if($op_stocks){
        $option_chain_time = $GLOBALS["option_chain_time"];
        $option_chain_timestamp = $GLOBALS["option_chain_timestamp"];
        $nxt_th_month = $GLOBALS["nxt_th_month"];
     
        // $cap_mon = strtoupper(date('M', strtotime('29-Dec-2022')));
        // //echo $cap_mon;
        // //echo strtoupper(date("dMY", strtotime('29-Dec-2022'))); exit;
        

        $last_expiry = strtotime(date("d/m/Y", strtotime($nxt_th_month)) . "last thu of this month"); 
        //echo strtotime(date("H:i")).'<br />';; 
        //echo strtotime(date("09:15")).'<br />';; 
        //echo strtotime(date("15:30")).'<br />';; 
        if(strtotime(date("00:15")) <=  strtotime(date("H:i")) && strtotime(date("22:30")) >=  strtotime(date("H:i"))){
            
                // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
                $ch = curl_init();
                // //echo "https://www.nseindia.com/api/option-chain-equities?symbol=$op_stocks";
                $ch = curl_init("https://www.nseindia.com/api/option-chain-equities?symbol=$op_stocks");
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

                $headers = array();
                $headers[] = 'Cache-Control: no-cache';
                // $headers[] = 'Content-Type: application/json';
                $headers[] = 'Postman-Token: e6041a48-275c-873e-cbe9-30d10d2b1916';
                curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

                $result = curl_exec($ch);
                if (curl_errno($ch)) {
                    //echo 'Error:' . curl_error($ch);
                }
                curl_close($ch);



                $in_arr = array("01-Sep-2022","08-Sep-2022","15-Sep-2022","22-Sep-2022","29-Sep-2022");

                $op_all_data = json_decode($result);
                // //echo '<pre>';
                // print_r($op_all_data);
                // //echo '</pre>'; exit;
                if(!isset($op_all_data->records->expiryDates)){
                    if($req_count < 10){
                        ?>
                        <script type="text/javascript">
                                setTimeout(function(){
                                        get_op_indices($indice,Number('<?php //echo $req_count ?>') + 1);
                                },1000);
                            </script>
                        <?php
                    } else {
                        //send mail
                        // the message
                        $msg = "";

                        // use wordwrap() if lines are longer than 70 characters
                        $msg = wordwrap($msg,70);

                        // send email
                        mail("someone@example.com","My subject",$msg);
                    }

                    // get_op_indices($indice);
                } else {
                    $ovl_data = array();
                    $option_expiry = array();
                    $expiry_limit = 10;
                    if($op_all_data->records->data){
                        foreach($op_all_data->records->data as $option_data){
                                if($last_expiry >= strtotime($option_data->expiryDate)){
                                    $underlyingValue = '';
                                    $option_instrument = '';
                                    if(isset($option_data->PE)){
                                        $underlyingValue = $option_data->PE->underlyingValue;
                                        $option_instrument = $option_data->PE->underlying;
                                    }else if(isset($option_data->CE)){
                                        $underlyingValue = isset($option_data->CE) ? $option_data->CE->underlyingValue : '';
                                        $option_instrument = isset($option_data->CE) ? $option_data->CE->underlying : '';
                                    }
                                    if(!isset($option_expiry[$option_data->expiryDate])){
                                        $option_expiry[$option_data->expiryDate] = array(
                                            "futuresPrice"  =>  $underlyingValue,
                                            "iv" => "0.0",
                                            "lotsize" => "50",
                                            "spotPrice" => 0,
                                            "option_timestamp"  =>  $option_chain_timestamp,
                                            "option_datetime"   =>  $option_chain_time,
                                            "option_expiry" =>  strtoupper(date("dMY", strtotime($option_data->expiryDate))),
                                            "option_instrument" =>  $option_instrument, 
                                        );
                                    } 
                                    if(isset($option_expiry[$option_data->expiryDate])){
                                        $option_expiry[$option_data->expiryDate]["optionchaindata"][] = array(
                                            "CallDelta" => "-" ,
                                            "CallIV" => isset($option_data->CE) ? $option_data->CE->impliedVolatility : "-",
                                            "CallLTP" => isset($option_data->CE) ? $option_data->CE->lastPrice : "-",
                                            "CallVega" => "-",
                                            "CallOpenIntrest"   => isset($option_data->CE) ? $option_data->CE->openInterest : "-",
                                            "CallChangeinOpenInterest"  =>  isset($option_data->CE) ? $option_data->CE->changeinOpenInterest : "-",
                                            "CallTotalTradedVolume" =>  isset($option_data->CE) ? $option_data->CE->totalTradedVolume : "-",
                                            "CallTotalBuyQuantity"  =>  isset($option_data->CE) ? $option_data->CE->totalBuyQuantity : "-",
                                            "CallTotalSellQuantity" =>  isset($option_data->CE) ? $option_data->CE->totalSellQuantity : "-",
                                            "PutDelta" => "-",
                                            "PutIV" => isset($option_data->PE) ? $option_data->PE->impliedVolatility : "-",
                                            "PutLTP" => isset($option_data->PE) ? $option_data->PE->impliedVolatility : "-",
                                            "PutVega" => "-",
                                            "PutOpenIntrest"   => isset($option_data->PE) ? $option_data->PE->openInterest : "-",
                                            "PutChangeinOpenInterest"  =>  isset($option_data->PE) ? $option_data->PE->changeinOpenInterest : "-",
                                            "PutTotalTradedVolume" =>  isset($option_data->PE) ? $option_data->PE->totalTradedVolume : "-",
                                            "PutTotalBuyQuantity"  =>  isset($option_data->PE) ? $option_data->PE->totalBuyQuantity : "-",
                                            "PutTotalSellQuantity" =>  isset($option_data->PE) ? $option_data->PE->totalSellQuantity : "-",
                                            "Strikes" => $option_data->strikePrice,
                                            "index_x" => 0,
                                            "index_y" => 0,
                                            "name" =>  0,

                                        );
                                    }
                                    

                                }
                        }
                    }
                    
                    //echo '<pre>';
                    print_r($option_expiry);
                    //echo '</pre>'; exit;
                    foreach($option_expiry as $option_exp_date => $option_data){
                        $fp = fopen("option_data/".$option_data["option_instrument"] .'-'.$option_exp_date.'-1.json', 'a');//opens file in append mode  
                        // fwrite($fp, '//'.$s_time.'---------'.date("Y-m-d H:i:s", $s_time).PHP_EOL); 
                        // fwrite($fp, '//'.$uurl.PHP_EOL); 
                        
                       fwrite($fp, json_encode($option_data).'#'.PHP_EOL);  
                        fclose($fp); 
                       // chmod($fp, 0777); 
                        //echo json_encode($option_data);
                    }
                   

                    
                }
       
            
        }else {
            //echo "time not come";
        }
        } else {
            //echo "indice not found";
        }
    
} */

 function get_op_indices($indice, $req_count){
    
    if($indice){
        if($indice == "NIFTY" || $indice == "BANKNIFTY"){
            $option_url = "https://www.nseindia.com/api/option-chain-indices?symbol=$indice";
        } else {
            $option_url = "https://www.nseindia.com/api/option-chain-equities?symbol=$indice";
        }
        $option_chain_time = $GLOBALS["option_chain_time"];
        $option_chain_timestamp = $GLOBALS["option_chain_timestamp"];
        $nxt_th_month = $GLOBALS["nxt_th_month"];
     
        // $cap_mon = strtoupper(date('M', strtotime('29-Dec-2022')));
        // //echo $cap_mon;
        // //echo strtoupper(date("dMY", strtotime('29-Dec-2022'))); exit;
        $date = new \DateTime($nxt_th_month);
        $date->modify('last thu of this month');
        $last_expiry = strtotime($date->format('Y-m-d')); 


        // $last_expiry = strtotime(date("d/m/Y", strtotime($nxt_th_month)) . "last thu of this month"); 
        //15-30/5 9-15 * * 1-5
        //*/5 9-16 * * 1-5  http://localhost/task/trade_sample/welcome/get_op
        // //echo strtotime(date("H:i")).'<br />';; 
        // //echo strtotime(date("09:15")).'<br />';; 
        // //echo strtotime(date("15:30")).'<br />';; 
        if(strtotime(date("00:16")) <=  strtotime(date("H:i")) && strtotime(date("23:29")) >=  strtotime(date("H:i"))){
            
                // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

                // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
                $ch = curl_init();

                curl_setopt($ch, CURLOPT_URL, $option_url);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

                curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

                $headers = array();
                $headers[] = 'Authority: www.nseindia.com';
                $headers[] = 'path: /api/option-chain-indices?symbol=NIFTY';
                $headers[] = 'scheme: https';
                $headers[] = 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
                $headers[] = 'Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Google Chrome\";v=\"96\"';
                $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
                $headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36';
                $headers[] = 'Sec-Ch-Ua-Platform: \"Linux\"';
                $headers[] = 'Accept: */*';
                $headers[] = 'Sec-Fetch-Site: cross-site';
                $headers[] = 'Sec-Fetch-Mode: cors';
                $headers[] = 'Sec-Fetch-Dest: empty';
                $headers[] = 'Referer: https://www.nseindia.com/';
                $headers[] = 'Accept-Language: en-US,en;q=0.9,ta;q=0.8';
                $headers[] = 'Cookie: '.$GLOBALS['set_cookiee'];
                $headers[] = 'If-None-Match: W/\"247-183c70b6f98\"';
                $headers[] = 'If-Modified-Since: Tue, 11 Oct 2022 12:35:59 GMT';
                $headers[] = 'Connection: keep-alive';
                $headers[] = 'Origin: https://www.nseindia.com';
                curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

                $result = curl_exec($ch);
                if (curl_errno($ch)) {
                    //echo 'Error:' . curl_error($ch);
                }
                curl_close($ch);



                $in_arr = array("01-Sep-2022","08-Sep-2022","15-Sep-2022","22-Sep-2022","29-Sep-2022");

                $op_all_data = json_decode($result);
                // echo '<pre>';
                // print_r($op_all_data);
                // echo '</pre>'; exit;
                if(!isset($op_all_data->records->expiryDates)){
                    // //echo '---';
                    // get_op_indices($indice);
                    if($req_count < 10){
                        ?>
                        <script type="text/javascript">
                                setTimeout(function(){
                                        get_op_indices($indice,Number('<?php //echo $req_count ?>') + 1);
                                },1000);
                            </script>
                        <?php
                    } else {
                        //send mail
                        // the message
                        $msg = "$indice data not get from NSE for".$GLOBALS['option_chain_time'];

                        // use wordwrap() if lines are longer than 70 characters
                        $msg = wordwrap($msg,70);

                        // send email
                        mail("ashok.a021092@gmail.com","Missing Option Data ".$indice,$msg);
                        exit;
                    }

                } else {
                    $ovl_data = array();
                    $option_expiry = array();
                    $expiry_limit = 10;
                    if($op_all_data->records->data){
                        $underlyingValue = 0;
                        if(isset($op_all_data->records->data[0]->CE)){
                            $underlyingValue = $op_all_data->records->data[0]->CE->underlyingValue;
                        } else if(isset($op_all_data->records->data[0]->PE)){
                            $underlyingValue = $op_all_data->records->data[0]->PE->underlyingValue;
                        } 
                            $get_today_open_spot_data = get_spot_price($GLOBALS['get_spot_price_symbol'][$indice]);
                            $option_expiry = array(
                                "futuresPrice"  =>  $underlyingValue,
                                "iv" => "0.0",
                                "lotsize" => "50",
                                "day_open" => $get_today_open_spot_data->open,
                                "previous_close" => $get_today_open_spot_data->previousClose,
                                "option_timestamp"  =>  $option_chain_timestamp,
                                "spot_price"    =>  $get_today_open_spot_data->lastPrice,
                                "option_datetime"   =>  $option_chain_time,
                                // "option_expiry" =>  strtoupper(date("dMY", strtotime($option_data->expiryDate))),
                                "option_instrument" =>  $indice, 
                                "option_date"  => date("Y-m-d")
                            );
                            // $option_expiry_array = $option_expiry["option_data_list"][ date("Y-m-d")][date("H:i")][strtoupper(date("Y-m-d", strtotime($option_data->expiryDate)))] = array();
                            // echo '<pre>';
                            // print_r($option_expiry);
                            // echo '</pre>'; exit;
                        foreach($op_all_data->records->data as $option_data){
                            // //echo '<pre>';
                            // print_r($option_data);
                            // //echo '</pre>';
                                if($last_expiry >= strtotime($option_data->expiryDate)){
                                    
                                    // $option_instrument = '';
                                    // if(isset($option_data->PE)){
                                    //     $underlyingValue = $option_data->PE->underlyingValue;
                                    //     $option_instrument = $option_data->PE->underlying;
                                    // }else if(isset($option_data->CE)){
                                    //     $underlyingValue = isset($option_data->CE) ? $option_data->CE->underlyingValue : '';
                                    //     $option_instrument = isset($option_data->CE) ? $option_data->CE->underlying : '';
                                    // }
                                    if(!isset($option_expiry["option_data_list"][ date("Y-m-d")][date("H:i")][strtoupper(date("Y-m-d", strtotime($option_data->expiryDate)))])){
                                         $option_expiry["option_data_list"][ date("Y-m-d")][date("H:i")][strtoupper(date("Y-m-d", strtotime($option_data->expiryDate)))] = array();
                                    }
                                   
                                    // echo '<pre>';
                                    // echo $option_data->expiryDate;
                                    // print_r($option_data);
                                    // echo '</pre>'; exit;
                                    // if(!isset($option_expiry[$option_data->expiryDate])){
                                    //     $get_today_open_spot_data = get_spot_price($GLOBALS['get_spot_price_symbol'][$option_instrument]);
                                    //     $option_expiry[$option_data->expiryDate] = array(
                                    //         "futuresPrice"  =>  $underlyingValue,
                                    //         "iv" => "0.0",
                                    //         "lotsize" => "50",
                                    //         "day_open" => $get_today_open_spot_data->open,
                                    //         "previous_close" => $get_today_open_spot_data->previousClose,
                                    //         "option_timestamp"  =>  $option_chain_timestamp,
                                    //         "spot_price"    =>  $get_today_open_spot_data->lastPrice,
                                    //         "option_datetime"   =>  $option_chain_time,
                                    //         "option_expiry" =>  strtoupper(date("dMY", strtotime($option_data->expiryDate))),
                                    //         "option_instrument" =>  $option_instrument, 
                                    //         "option_date"  => date("Y-m-d")
                                    //     );
                                    // } 
                                     if(isset($option_expiry["option_data_list"][ date("Y-m-d")][date("H:i")][strtoupper(date("Y-m-d", strtotime($option_data->expiryDate)))])){
                                        // echo '<pre>';
                                        // print_r($option_data);
                                        // echo '</pre>'; exit;
                                        //$option_expiry["optionchaindata"][] = 
                                        $option_expiry["option_data_list"][ date("Y-m-d")][date("H:i")][strtoupper(date("Y-m-d", strtotime($option_data->expiryDate)))][] = array(
                                            "call_iv" => isset($option_data->CE) ? $option_data->CE->impliedVolatility : "-",
                                            "call_ltp" => isset($option_data->CE) ? $option_data->CE->lastPrice : "-",
                                            "call_oi"   => isset($option_data->CE) ? $option_data->CE->openInterest : "-",
                                            "call_change_oi"  =>  isset($option_data->CE) ? $option_data->CE->changeinOpenInterest : "0",
                                            "call_total_traded_volume" =>  isset($option_data->CE) ? $option_data->CE->totalTradedVolume : "0",
                                            "call_total_buy_quantity"  =>  isset($option_data->CE) ? $option_data->CE->totalBuyQuantity : "0",
                                            "call_total_sell_quantity" =>  isset($option_data->CE) ? $option_data->CE->totalSellQuantity : "0",
                                            "call_change_price" =>  isset($option_data->CE) ? $option_data->CE->change : "0",
                                            "call_pchange_price" =>  isset($option_data->CE) ? $option_data->CE->pChange : "0",
                                            "call_bid_qty" => isset($option_data->CE) ? $option_data->CE->bidQty : "0",
                                            "call_bid_price" =>  isset($option_data->CE) ? $option_data->CE->bidprice : "0",
                                            "call_ask_qty" => isset($option_data->CE) ? $option_data->CE->askQty : "0",
                                            "call_ask_price" =>  isset($option_data->CE) ? $option_data->CE->askPrice : "0",
                                            "put_iv" => isset($option_data->PE) ? $option_data->PE->impliedVolatility : "0",
                                            "put_ltp" => isset($option_data->PE) ? $option_data->PE->lastPrice : "0",
                                            "put_oi"   => isset($option_data->PE) ? $option_data->PE->openInterest : "0",
                                            "put_change_oi"  =>  isset($option_data->PE) ? $option_data->PE->changeinOpenInterest : "0",
                                            "put_total_traded_volume" =>  isset($option_data->PE) ? $option_data->PE->totalTradedVolume : "0",
                                            "put_total_buy_quantity"  =>  isset($option_data->PE) ? $option_data->PE->totalBuyQuantity : "0",
                                            "put_total_sell_quantity" =>  isset($option_data->PE) ? $option_data->PE->totalSellQuantity : "0",
                                            "put_change_price" =>  isset($option_data->PE) ? $option_data->PE->change : "0",
                                            "put_pchange_price" =>  isset($option_data->PE) ? $option_data->PE->pChange : "0",
                                            "put_bid_qty" => isset($option_data->PE) ? $option_data->PE->bidQty : "0",
                                            "put_bid_price" =>  isset($option_data->PE) ? $option_data->PE->bidprice : "0",
                                            "put_ask_qty" => isset($option_data->PE) ? $option_data->PE->askQty : "0",
                                            "put_ask_price" =>  isset($option_data->PE) ? $option_data->PE->askPrice : "0",
                                            "strike" => $option_data->strikePrice,
                                           

                                        );
                    //                     echo '<pre>';
                    // print_r($option_expiry);
                    // // print_r($option_expiry_array);
                    // echo '</pre>';  exit;
                                    }


                                }
                        }
                    }
                    
                    // echo '<pre>';
                    // echo "dsfsdf";
                    // print_r($option_expiry);
                    // echo '</pre>';  exit;
                    $fp = fopen("option_data/".date("Y-m-d")."-".$indice.".json", 'a');//opens file in append mode  
                        // fwrite($fp, '//'.$s_time.'---------'.date("Y-m-d H:i:s", $s_time).PHP_EOL); 
                        // fwrite($fp, '//'.$uurl.PHP_EOL); 
                        
                       fwrite($fp, json_encode($option_expiry).'#'.PHP_EOL);  
                        fclose($fp); 
                    // foreach($option_expiry as $option_exp_date => $option_data){
                    //     $fp = fopen("option_data/".date("Y-m-d")."-".$indice.".json", 'a');//opens file in append mode  
                    //     // fwrite($fp, '//'.$s_time.'---------'.date("Y-m-d H:i:s", $s_time).PHP_EOL); 
                    //     // fwrite($fp, '//'.$uurl.PHP_EOL); 
                        
                    //    fwrite($fp, json_encode($option_expiry).'#'.PHP_EOL);  
                    //     fclose($fp); 
                    //    // chmod($fp, 0777); 
                    //     //echo json_encode($option_data);
                    // }
                   

                    
                }
       echo "success";
            
        }else {
            echo "time not come";
        }
        } else {
            echo "indice not found";
        }
    
    
} 

function get_nse_cookie(){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://www.nseindia.com/option-chain');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
    curl_setopt($ch, CURLOPT_HEADER, 1);

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $response = curl_exec($ch);
    $header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    $header = substr($response, 0, $header_size);
    $body = substr($response, $header_size);
    if (curl_errno($ch)) {
        //echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    return get_headers_from_curl_response($response);
}


function get_headers_from_curl_response($response)
{
    $headers = array();
    $cookie_set = '';
    $header_text = substr($response, 0, strpos($response, "\r\n\r\n"));
//     //echo '<pre>';
//     print_r(explode("\r\n", $header_text));
// //echo '</pre>'; exit;
    foreach (explode("\r\n", $header_text) as $i => $line)
        // //echo $line;
        if ($i === 0)
            $headers['http_code'] = $line;
        else
        {
            // foreach(explode(': ', $line) as $co_key => $co_value){
            //     //echo '<pre>';
            //     // print_r($co_key);
            //     print_r($co_value);
            //     //echo '</pre>';
            // }
            list ($key, $value) = explode(': ', $line);
            // if($key == "set-cookie"){
            //     $cookie_set .= $value;
            // } else {
            //     $headers[$key] = $value;
            // }
            if(isset($headers[$key])){
                $headers[$key] .= $headers[$key].";".$value;
            } else {
                $headers[$key] = $value;
            }
        }
// //echo $cookie_set;
    return $headers;
}


function get_stocks_spot_price($stock_name){
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    // echo "https://www.nseindia.com/api/equity-stockIndices?index=".$indice_name;
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, "https://www.nseindia.com/api/historical/cm/equity?symbol=".$stock_name);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Authority: www.nseindia.com';
    $headers[] = 'Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Google Chrome\";v=\"96\"';
    $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
    $headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36';
    $headers[] = 'Sec-Ch-Ua-Platform: \"Linux\"';
    $headers[] = 'Accept: */*';
    $headers[] = 'Sec-Fetch-Site: cross-site';
    $headers[] = 'Sec-Fetch-Mode: cors';
    $headers[] = 'Sec-Fetch-Dest: empty';
    $headers[] = 'Referer: https://www.nseindia.com/';
    $headers[] = 'Accept-Language: en-US,en;q=0.9,ta;q=0.8';
    $headers[] = 'Cookie: '.$GLOBALS['set_cookiee'];
    $headers[] = 'If-None-Match: W/\"247-183c70b6f98\"';
    $headers[] = 'If-Modified-Since: Tue, 11 Oct 2022 12:35:59 GMT';
    $headers[] = 'Connection: keep-alive';
    $headers[] = 'Origin: https://www.nseindia.com';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);


    // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $response = curl_exec($ch);
    // $header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    // $header = substr($response, 0, $header_size);
    // $body = substr($response, $header_size);
    if (curl_errno($ch)) {
        //echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
   // echo '<pre>';
   // print_r(json_decode($response)); 
   // echo '</pre>';
   return json_decode($response)->data[0]; 
   // echo '</pre>'; exit;
}

function get_spot_price($indice_name){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    // echo "https://www.nseindia.com/api/equity-stockIndices?index=".$indice_name;
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, "https://www.nseindia.com/api/equity-stockIndices?index=".$indice_name);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Authority: www.nseindia.com';
    $headers[] = 'Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Google Chrome\";v=\"96\"';
    $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
    $headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36';
    $headers[] = 'Sec-Ch-Ua-Platform: \"Linux\"';
    $headers[] = 'Accept: */*';
    $headers[] = 'Sec-Fetch-Site: cross-site';
    $headers[] = 'Sec-Fetch-Mode: cors';
    $headers[] = 'Sec-Fetch-Dest: empty';
    $headers[] = 'Referer: https://www.nseindia.com/';
    $headers[] = 'Accept-Language: en-US,en;q=0.9,ta;q=0.8';
    $headers[] = 'Cookie: '.$GLOBALS['set_cookiee'];
    $headers[] = 'If-None-Match: W/\"247-183c70b6f98\"';
    $headers[] = 'If-Modified-Since: Tue, 11 Oct 2022 12:35:59 GMT';
    $headers[] = 'Connection: keep-alive';
    $headers[] = 'Origin: https://www.nseindia.com';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);


    // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $response = curl_exec($ch);
    // $header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    // $header = substr($response, 0, $header_size);
    // $body = substr($response, $header_size);
    if (curl_errno($ch)) {
        //echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
   // echo '<pre>';
   // print_r(json_decode($response)); 
   // echo '</pre>';
   return json_decode($response)->data[0]; 
   // echo '</pre>'; exit;
}
// exit;

// $nxt_th_month = date('d/m/Y', strtotime('+3 months')); 

// //echo strtotime(date("d/m/Y", strtotime($nxt_th_month)) . "last thu of this month"); exit;
// //echo '<br />';
// //echo strtotime("03-Nov-2022");  exit;
// foreach ($option_indice  as $key => $indice) {
//     // code...
//     get_op_indices($indice);
// }
if(!in_array(date("Y-m-d"), $GLOBALS["ignore_dates"] )){
	if(strtotime(date("00:16")) <=  strtotime(date("H:i")) && strtotime(date("23:29")) >=  strtotime(date("H:i"))){
       foreach ($option_stocks  as $key => $op_stocks) {
               // code...
               get_op_indices($op_stocks,0);
       }
    } else {
      echo "not time yet come";
    }
} else {
  echo "leave day";
}


// $nss = get_nse_cookie();
// //echo '<pre>';
// print_r($nss);
// //echo '</pre>';
?>